import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { ReCaptchaProvider } from "@/components/ReCaptchaProvider";
import { Footer } from "@/components/Footer";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased pt-16 flex flex-col min-h-screen`}
      >
        <ReCaptchaProvider>
          <Navigation />
          <div className="flex-1">{children}</div>
          <Footer />
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
