import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased pb-20 pt-16`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
